// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using polisync.Data;

#nullable disable

namespace polisync.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715144415_InitialCreateWithSeededTables")]
    partial class InitialCreateWithSeededTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PolicyUserModel", b =>
                {
                    b.Property<string>("PoliciesPolicyType")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PoliciesPolicyType", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("PolicyUserModel");
                });

            modelBuilder.Entity("polisync.Models.InsuranceClaim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClaimId");

                    b.HasIndex("PolicyType");

                    b.HasIndex("UserId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            ClaimAmount = 250000m,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2026, 4, 13, 22, 50, 0, 0, DateTimeKind.Unspecified),
                            IncidentDescription = "Laptop Theft",
                            PolicyType = "Property",
                            Status = "Submitted",
                            UserId = 3
                        },
                        new
                        {
                            ClaimId = 2,
                            ClaimAmount = 120000m,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2026, 5, 29, 15, 3, 0, 0, DateTimeKind.Unspecified),
                            IncidentDescription = "Bodily Injury At Work",
                            PolicyType = "WIBA",
                            Status = "Submitted",
                            UserId = 1
                        },
                        new
                        {
                            ClaimId = 3,
                            ClaimAmount = 1000000m,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2026, 7, 1, 10, 32, 0, 0, DateTimeKind.Unspecified),
                            IncidentDescription = "Car Accident",
                            PolicyType = "Motor",
                            Status = "Submitted",
                            UserId = 2
                        },
                        new
                        {
                            ClaimId = 4,
                            ClaimAmount = 1000000m,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2026, 7, 5, 10, 32, 0, 0, DateTimeKind.Unspecified),
                            IncidentDescription = "Baggage Loss",
                            PolicyType = "Travel",
                            Status = "Submitted",
                            UserId = 8
                        },
                        new
                        {
                            ClaimId = 5,
                            ClaimAmount = 50000m,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2026, 5, 26, 12, 8, 0, 0, DateTimeKind.Unspecified),
                            IncidentDescription = "Motor Windshield Replacement",
                            PolicyType = "Motor",
                            Status = "Submitted",
                            UserId = 2
                        },
                        new
                        {
                            ClaimId = 6,
                            ClaimAmount = 200000m,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2026, 4, 7, 21, 33, 0, 0, DateTimeKind.Unspecified),
                            IncidentDescription = "Medical Surgery",
                            PolicyType = "Health",
                            Status = "Submitted",
                            UserId = 4
                        },
                        new
                        {
                            ClaimId = 7,
                            ClaimAmount = 100000m,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2026, 5, 29, 14, 17, 0, 0, DateTimeKind.Unspecified),
                            IncidentDescription = "Equipment Damage",
                            PolicyType = "Property",
                            Status = "Submitted",
                            UserId = 1
                        },
                        new
                        {
                            ClaimId = 8,
                            ClaimAmount = 75000m,
                            CreatedAt = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2026, 6, 29, 20, 4, 0, 0, DateTimeKind.Unspecified),
                            IncidentDescription = "Cancelled Flight",
                            PolicyType = "Travel",
                            Status = "Submitted",
                            UserId = 8
                        });
                });

            modelBuilder.Entity("polisync.Models.Policy", b =>
                {
                    b.Property<string>("PolicyType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PolicyLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PolicyType");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            PolicyType = "Health",
                            EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyLimit = 15000000m,
                            PolicyName = "HEALTH/4/2023",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PolicyType = "Motor",
                            EndDate = new DateTime(2027, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyLimit = 25000000m,
                            PolicyName = "MOTOR/1/2024",
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PolicyType = "Property",
                            EndDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyLimit = 7500000m,
                            PolicyName = "PROPERTY/2/2023",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PolicyType = "Travel",
                            EndDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyLimit = 2500000m,
                            PolicyName = "TRAVEL/4/2022",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PolicyType = "WIBA",
                            EndDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyLimit = 10000000m,
                            PolicyName = "WIBA/1/2025",
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("polisync.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "allan.doe@email.com",
                            Name = "Allan Doe",
                            Password = "Allan@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "beth.doe@email.com",
                            Name = "Beth Doe",
                            Password = "Beth@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "charles.doe@email.com",
                            Name = "Charles Doe",
                            Password = "Charles@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "diana.doe@email.com",
                            Name = "Diana Doe",
                            Password = "Diana@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "edward.doe@email.com",
                            Name = "Edward Doe",
                            Password = "Edward@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "faith.doe@email.com",
                            Name = "Faith Doe",
                            Password = "Faith@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "gerald.doe@email.com",
                            Name = "Gerald Doe",
                            Password = "Gerald@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "hannah.doe@email.com",
                            Name = "Hannah Doe",
                            Password = "Hannah@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "ivy.doe@email.com",
                            Name = "Ivy Doe",
                            Password = "Ivy@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 10,
                            Email = "john.doe@email.com",
                            Name = "John Doe",
                            Password = "John@123!",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 11,
                            Email = "kellen.smith@polisync.com",
                            Name = "Kellen Smith",
                            Password = "Kellen@123!",
                            Role = "Administrator"
                        },
                        new
                        {
                            UserId = 12,
                            Email = "larry.smith@polisync.com",
                            Name = "Larry Smith",
                            Password = "Larry@123!",
                            Role = "Administrator"
                        });
                });

            modelBuilder.Entity("PolicyUserModel", b =>
                {
                    b.HasOne("polisync.Models.Policy", null)
                        .WithMany()
                        .HasForeignKey("PoliciesPolicyType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("polisync.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("polisync.Models.InsuranceClaim", b =>
                {
                    b.HasOne("polisync.Models.Policy", "Policy")
                        .WithMany("InsuranceClaims")
                        .HasForeignKey("PolicyType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("polisync.Models.UserModel", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("polisync.Models.Policy", b =>
                {
                    b.Navigation("InsuranceClaims");
                });

            modelBuilder.Entity("polisync.Models.UserModel", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
